### PR TITLE
Add backend to test matrix

### PR DESCRIPTION
**Pull request by bveeramani**

### CODE REVIEW

**Review by elibol — APPROVED** [review]
Perfect. There are some duplicate tests that are triggered, but this can be fixed. If tests pass then LGTM.

**Comment by bveeramani** [comment]
> Perfect. There are some duplicate tests that are triggered, but this can be fixed. If tests pass then LGTM.

Which duplicate tests are you referring to?

**Comment by bveeramani** [comment]
Also, I'm almost certain `test/pytest (ray, 3.7)` is stalling because of an issue related to #263. If it's okay with you, I'll merge this PR despite `test/pytest (ray, 3.7)` timing out

**Comment by elibol** [comment]
> Also, I'm almost certain `test/pytest (ray, 3.7)` is stalling because of an issue related to #263. If it's okay with you, I'll merge this PR despite `test/pytest (ray, 3.7)` timing out

Can we wait/rerun just to be certain?

**Comment by elibol** [comment]
> > Perfect. There are some duplicate tests that are triggered, but this can be fixed. If tests pass then LGTM.
> 
> Which duplicate tests are you referring to?

Anything which doesn't rely on an `ArrayApplication` fixture, e.g. `tests.core.test_app_manager`

**Comment by bveeramani** [comment]
> 



> > > Perfect. There are some duplicate tests that are triggered, but this can be fixed. If tests pass then LGTM.
> > 
> > 
> > Which duplicate tests are you referring to?
> 
> Anything which doesn't rely on an `ArrayApplication` fixture, e.g. `tests.core.test_app_manager`

Gotcha. Yeah, this should be pretty straightforward to do in a follow-up PR

**Comment by bveeramani** [comment]
> > Also, I'm almost certain `test/pytest (ray, 3.7)` is stalling because of an issue related to #263. If it's okay with you, I'll merge this PR despite `test/pytest (ray, 3.7)` timing out
> 
> Can we wait/rerun just to be certain?

Yeah, that's fine. Re-running now

**Pull request merged**
